language: java

# 07-Sep-2017, tatu: Alas, jdk6 just doesn't work. First was missing JDK6 pkg
#   but then Maven itself, or one of plugins, compiled with later. So... just leave
jdk:
  - openjdk8

# whitelist
branches:
  only:
    - master
    - "2.11"
