language: java

# 27-Sep-2017, tatu: Older versions should compile with Java 6; but with 3.x as master
#   only Java 8 and beyond work
jdk:
  - openjdk8
  - oraclejdk9

# whitelist
branches:
  only:
    - master
    - "2.9"
